# Generated by Django 5.1.3 on 2024-11-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrackapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktrackuser',
            name='profile_img',
            field=models.URLField(blank=True, default=''),
        ),
    ]
