# Generated by Django 5.1.4 on 2024-12-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrackapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.TextField(default='Unknown Item')),
                ('part_number', models.IntegerField(unique=True)),
                ('supplier_id', models.IntegerField()),
                ('lead_time', models.IntegerField(default=2)),
                ('inbound_price', models.FloatField()),
                ('outbound_price', models.FloatField()),
                ('stock_level', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.TextField(default='Unknown Item')),
                ('part_number', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('due_date', models.DateField()),
                ('created', models.DateField()),
                ('value', models.FloatField()),
                ('customer_id', models.TextField(default='Unknown Item')),
                ('is_outbound', models.BooleanField()),
                ('status', models.TextField(default='Pending')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField()),
                ('supplier_name', models.TextField(default='default value')),
            ],
        ),
        migrations.AlterField(
            model_name='stocktrackuser',
            name='profile_img',
            field=models.URLField(blank=True, default=''),
        ),
    ]
