# Generated by Django 5.1.4 on 2024-12-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrackapi', '0002_part_purchaseorder_suppliers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='PO_number',
        ),
        migrations.AddField(
            model_name='part',
            name='lead_time',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='part',
            name='part_name',
            field=models.TextField(default='Unknown Item'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='part_name',
            field=models.TextField(default='Unknown Item'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='customer_id',
            field=models.TextField(default='Unknown Item'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='part_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
