# Generated by Django 5.1.3 on 2024-12-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrackapi', '0002_alter_stocktrackuser_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField(unique=True)),
                ('supplier_id', models.IntegerField()),
                ('inbound_price', models.FloatField()),
                ('outbound_price', models.FloatField()),
                ('stock_level', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_number', models.IntegerField()),
                ('part_number', models.TextField(default='default value')),
                ('manufacturer_id', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('qty', models.IntegerField()),
                ('due_date', models.DateField()),
                ('created', models.DateField()),
                ('value', models.FloatField()),
                ('customer_id', models.IntegerField()),
                ('movement_type', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
