# Generated by Django 5.1.4 on 2024-12-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrackapi', '0003_part_purchaseorder_delete_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_ID', models.IntegerField()),
                ('manufacturer_name', models.TextField(default='default value')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_ID', models.IntegerField()),
                ('supplier_name', models.TextField(default='default value')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='movement_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_outbound',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
