# Generated by Django 5.1.4 on 2024-12-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrackapi', '0004_manufacturers_suppliers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturers',
            old_name='manufacturer_ID',
            new_name='manufacturer_id',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='supplier_ID',
            new_name='supplier_id',
        ),
    ]
