# Generated by Django 5.1.4 on 2024-12-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrackapi', '0004_part_lead_time_part_part_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='part_number',
            field=models.IntegerField(),
        ),
    ]
