# Generated by Django 5.1.4 on 2024-12-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrackapi', '0005_rename_manufacturer_id_manufacturers_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='customer_id',
            field=models.TextField(default='default value'),
        ),
    ]
