# Generated by Django 5.1.4 on 2024-12-05 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrackapi', '0006_alter_purchaseorder_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
